Complete post/slides endpoint
CA-G12/mern-presently.io pull request #11
Opened 2022-10-19 07:36 UTC by fadezak100

- Created a new route for slides
- Created a new controller related to slides
- Test slide controller

2022-10-19 19:28 UTC, AhmedSafi97 commented on src/controllers/SlideController.ts
> +    const { link, title, isPrivate, isLive } = req.body
where is validation ya man

2022-10-19 19:29 UTC, AhmedSafi97 commented on src/controllers/SlideController.ts
> +}
check how @Zayan-Alaraishy is handling the errors here https://github.com/CA-G12/mern-presently.io/pull/10

2022-10-19 20:03 UTC, AhmedSafi97 commented on src/interfaces/SlideInterface.ts
> +  body: { title: string; link: string; isPrivate?: boolean; isLive?: boolean }
DRY your code by reusing some interfaces `body: CreatePresentationOptions`

2022-10-19 20:04 UTC, AhmedSafi97 commented on src/repositories/SlideRepository.ts
> +const createPresentation = (options: CreatePresentationOptions) =>
this should be called `presentation`
```js
Slide.create(presentation)
```

2022-10-19 20:07 UTC, AhmedSafi97 requested changes
Looks good, small changes then we are good to go

2022-10-19 20:42 UTC, moustf reviewed
To be honest, I can not request any changes because I do not understand your code style, but thanks for putting me as a reviewer

2022-10-19 21:13 UTC, fadezak100 commented
> To be honest, I can not request any changes because I do not understand your code style, but thanks for putting me as a reviewer

Thank you for putting the time to review the code Mustafa! I appreciate it.

2022-10-20 11:12 UTC, AhmedSafi97 submitted a review, later dismissed

2022-10-22 20:12 UTC, nadasuhailAyesh12 approved these changes

2022-10-23 07:16 UTC, Zayan-Alaraishy submitted a review, later dismissed

2022-10-23 08:11 UTC, merged